version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify Node.js version
    commands:
      - echo "Installing dependencies"
      - npm install
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli # Install Angular CLI globally

  pre_build:
    commands:
      - echo "Running linting"
      - npm run lint # Ensure that the lint script exists
  
  build:
    commands:
      - echo "Starting the project"
      - npm run start # Replace with the correct script for running Juice Shop
  
  post_build:
    commands:
      - echo "Post-build actions"
      # Any post-build steps like packaging or deploying

artifacts:
  files:
    - '**/*'
  discard-paths: no
