name: Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t my-app .

    - name: Run Tests and Copy Coverage
      run: |
        docker run --rm --entrypoint /bin/bash \
          -v "$(pwd)/coverage:/app/coverage" \
          my-app \
          -c "
            set -e
            npm install && 
            npm run build &&
            npm run test || true
            
            if [ -f build/reports/coverage/api-tests/lcov.info ]; then
              mkdir -p /app/coverage
              cp build/reports/coverage/api-tests/lcov.info /app/coverage/
            else
              echo 'lcov.info bulunamadı'
            fi
          "

    - name: Run Semgrep Security Scan
      run: |
        docker run --rm -v $(pwd):/src returntocorp/semgrep --config auto /src

    - name: Upload Coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/