name: Docker Build and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t my-app .

    - name: Run Tests inside Docker Container
      run: |
        docker run --rm my-app /bin/sh -c "
          npm install && 
          npm run build &&
          npm run test || true &&

          # lcov.info dosyasını kopyalamaya çalış
          [ -f build/reports/coverage/api-tests/lcov.info ] && cp build/reports/coverage/api-tests/lcov.info api-lcov.info || echo 'lcov.info bulunamadı, kopyalama atlandı.'
        "

    - name: Run SamGrep Security Scan
      run: |
        docker run --rm -v $(pwd):/src returntocorp/semgrep --config auto /src

    - name: Upload Coverage (Opsiyonel)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: api-lcov.info
