name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job 1: Software Composition Analysis (SCA) with CycloneDX
  cyclonedx-sca:
    name: SCA with CycloneDX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install CycloneDX
        run: |
          curl -sSL https://raw.githubusercontent.com/CycloneDX/cyclonedx-java-cli/main/install.sh | bash
      - name: Generate CycloneDX BOM
        run: |
          cyclonedx-cli generate -o bom.xml --project "juiceshop"

  # Job 2: Container Image Scanning with Trivy
  container-scan:
    name: Trivy Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-app:latest .
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-app:latest

  # Job 3: Nuclei Vulnerability Scanning
  nuclei-scan:
    name: System Vulnerability Scanning with Nuclei
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Nuclei vulnerability scan
        run: |
          nuclei -u https://localhost:8080

  # Job 4: Deploy to Docker Desktop
  deploy-docker:
    name: Deploy to Docker Desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and Deploy Docker Image
        run: |
          docker build -t my-app:latest .
          docker run -d -p 8080:8080 my-app:latest

  # Job 5: Dynamic Application Security Testing (DAST) with Dastarly
  dastarly-scan:
    name: Run DAST with Dastarly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Dastarly scan
        run: |
          dastarly scan --target https://localhost:8080
